# Generated by Django 6.0.4 on 2026-05-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drawingtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.traderprofile')),
            ],
            options={
                'unique_together': {('owner', 'symbol')},
            },
        ),
    ]
