# Generated by Django 6.0.4 on 2026-05-31 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='XAU/USD', max_length=20)),
                ('interval', models.CharField(default='15m', max_length=20)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_state', to='core.traderprofile')),
            ],
        ),
    ]
