# Generated by Django 6.0.4 on 2026-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backtestsession_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstate',
            name='bar_spacing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
