# Generated by Django 6.0.5 on 2026-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chartstate_bar_spacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstate',
            name='indicators',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
