# Generated by Django 6.0.5 on 2026-08-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chartstate_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstate',
            name='favorite_timeframes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
