# Generated by Django 6.0.4 on 2026-09-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_favorite_timeframes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PineScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script_type', models.CharField(default='indicator', max_length=20)),
                ('code', models.TextField(blank=True)),
                ('versions', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pine_scripts', to='core.traderprofile')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
