# Generated by Django 6.0.4 on 2026-09-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pinescript'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrategyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_notes', to='core.traderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
